[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out" # Cambia "out" si tu directorio de salida es diferente

[build.environment]
  NODE_VERSION = "20" # Especifica la versión de Node.js que estás usando

[functions]
  # Opcional: Configuraciones específicas para funciones de Netlify
  node_bundler = "esbuild" # O puedes usar "webpack" dependiendo de tus necesidades

[[redirects]]
  # Opcional: Redirecciones si es necesario
  from = "/*"
  to = "/index.html"
  status = 200


